services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: br_massoterapia
      POSTGRES_USER: brmasso
      POSTGRES_PASSWORD: brmasso123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://brmasso:brmasso123@postgres:5432/br_massoterapia
    depends_on:
      - postgres
    ports:
      - "8000:8000"


  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/docker/volumes/infra_certbot_www/_data:/var/www/certbot
      - ./frontend:/usr/share/nginx/html:ro # <--- LINHA ADICIONADA DA LANDPAGE
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/docker/volumes/infra_certbot_www/_data:/var/www/certbot

volumes:
  postgres_data:
  infra_certbot_www:
    external: true
